### ISSUE TITLE
The extension does absolutly nothing

### ISSUE THREAD

**Issue by stemy2** [rugk/mastodon-simplified-federation#101]
## Bug description
I installed and configured the extension, but mastodon sites are working as if the extension wasn't there.

## Steps to reproduce

1. Install the extension
2. Configure the extension with an existing account
3. Go to a random mastodon site

### Actual behavior
The site asks me to login on the server or to copy-paste the toot url on my server's account.

### Expected behavior
I shouldn't have to do anything.

## System

Operating system and version: 
Browser and version: Firefox 110.0.1
Add-on version: 2.0

**Comment by rugk** [comment]
Which server (instance/URL) did you try it with and what is your home instance? Which mastodon instance do they use?

Could you please try fowling the mastodon power of the testing guide and report whether that works?
https://github.com/rugk/mastodon-simplified-federation/wiki/Testing#mastodon

**Comment by stemy2** [comment]
It works now.

**Comment by rugk** [comment]
If you encounter this or a different issue again, feel free to let me know.

**Comment by vaguerant** [comment]
I think the browser might need a restart before the extension starts working, possibly the cause here? I installed and set it up, and ... nothing, every external instance just behaving as they would normally. Was about to file an issue but figured I'd restart Firefox first, and upon reboot, everything seems to be working as expected. The setup instructions make no mention of a restart being needed, so might only be an issue under specific conditions?

Obviously I refreshed any open Mastodon tabs after installing to be sure the extension was active, but that didn't seem to be enough, only the full browser restart got it working for me. 

My setup:
- Windows 10
- Firefox 114.0.2 (64-bit)
- Mastodon – Simplified Federation! 2.0
- external instances tested were `mastodon.world` and `social.treehouse.systems`
- my local instance is `mastodon.social`

**Comment by rugk** [comment]
> Obviously I refreshed any open Mastodon tabs after installing to be sure the extension was active, but that didn't seem to be enough, only the full browser restart got it working for me.

Hmm, I was about to say, refreshing should work. Technically, when installed, a restart should not be different than a reload for the extension.

**Comment by SystemZ** [comment]
I had the same problem.
Probably restarting browser helps.
In my case after I entered my instance URL in settings, I turned off and on addon on `about:addons` and it started to work 👍
