### ISSUE TITLE
Cannot favorite Mastodon posts on other socials when my home instance is mastodon.social

### ISSUE THREAD

**Issue by coldReactive** [rugk/mastodon-simplified-federation#113]
## Bug description
Cannot favorite Mastodon posts on other socials when my home instance is mastodon.social

## Steps to reproduce
1. Go to: https://kind.social/@Ravynn
2. Click the Star (Favorite) Button on the post shown below:
![image](https://github.com/rugk/mastodon-simplified-federation/assets/1313673/e427ade6-72b8-40c3-9901-21d3163b0fc6)
4. Note that it redirects here: https://mastodon.social/authorize_interaction?uri=https://kind.social/users/Ravynn/statuses/110807184233380594/activity

### Actual behavior
Redirects to https://mastodon.social/authorize_interaction?uri=https://kind.social/users/Ravynn/statuses/110807184233380594/activity which cannot be found.

### Expected behavior
Favorites the post on mastodon.social as intended.

## System

Operating system and version: Windows 11
Browser and version: Firefox 115.0.3 (64-bit)
Add-on version: 2.0 (July 31st, 2023)

## Possible solution
None

**Comment by rugk** [comment]
Thanks a lot for reporting! Big question first: Does following still work?

Without having reproduced/confirmed it, my best guess and I am quite certain it is this, is that Mastodon has now also removed that landing/redirect page. Mastodon.social usually runs a pre-release version, so such things happen there first.

That would mean we really need to adjust the behavior of the extension. That may be https://github.com/rugk/mastodon-simplified-federation/issues/86, but actually even that is not enough, because in the proposed solution there, we would still redirect to. So no, this is related, but not actually _the thing_ we need to do.

Any help – also if it is just technical ideas/proposals/research on how we can now trigger a follow/interact page, where you can follow people would be helpful.

Maybe, we would need to redirect to the profile page for follows? And for interactions we somehow have to assemble the URl ourselve? There is no better way?
Also, if you find any reference/commits for the "landing page" removal, let me know. I don't have much hope, but we can at least ask for Mastodon to keep that page and let it in there for such a feature.

**Comment by coldReactive** [comment]
The thing is, FediAct works perfectly except when mastodon doesn't resolve instances. FediAct is also looking for someone to take over their extension, so you might want to consider doing that too.

**Comment by rugk** [comment]
Okay, that is a good information. As for this extension, does following still work, BTW though?

The thing I see about [FediAct](https://github.com/Lartsch/FediAct/) (was it called Graze at some time?) [is I have security concerns about the general architecture](https://github.com/rugk/mastodon-simplified-federation/issues/86#issuecomment-1353323405) – in case it is still done the way it was done in the past there (I have not checked that again), but you can read that in the link. The next thing about taking over maintenance would be that FediAct has much more features and maintaining it would thus come with a much larger burden and I already have problems getting up with this simpler extension here.

So while I am very thankful for your suggestion and note about that, I will not do that.

But that is off-topic anyway, let's focus on fixing the issue at hand. If you want to discuss that other thing [you can open a discussion](https://github.com/rugk/mastodon-simplified-federation/discussions).

**Comment by coldReactive** [comment]
Fediact doesn't open pop-ups. Graze is still graze: https://addons.mozilla.org/en-US/firefox/addon/graze/

Graze was never open source.

**Comment by rugk** [comment]
@coldReactive just tried to reproduce the issue using my testing account `@rugk_testing@mastodon.social` and I could not. Both your provided user account and others work, both following and interacting with toots.
However, given you were redirected to a wrong URL – https://mastodon.social/authorize_interaction?uri=https://kind.social/users/Ravynn/statuses/110807184233380594/activity (the `/activity` should not be there) –, I assume there is/was an issue similar to https://github.com/rugk/mastodon-simplified-federation/issues/93

As such, if you could reproduce it [with the soon to be released v2.1](https://github.com/rugk/mastodon-simplified-federation/milestone/7?closed=1) that would be helpful. If the issue still occurs, please provide the toot and exact STRs where it happens.

It is at least not a mastodon.social issue/issue about a beta software that I originally thought and I apologize for the confusion.

**Comment by rugk** [comment]
@coldReactive Could you try the latest update v2.1? [It has been released for some time now.](https://github.com/rugk/mastodon-simplified-federation/releases/tag/v2.1)
