### ISSUE TITLE
Extension causes lag on mapcomplete.org

### ISSUE THREAD

**Issue by thibaultmol** [rugk/mastodon-simplified-federation#129]
## Bug description
I seem to have massive lag problems (where firefox even complains after the tab freezes for a while that this extension is causing the problems)

## Steps to reproduce
Have simple fed extension installed and visit any of the mapcomplete theme's such as: https://mapcomplete.org/cyclofix

### Actual behavior
You'll that the page is very laggy and the devtools console will show errors related to this extension at some point as well 

### Expected behavior
no lag

## System

Operating system and version: 
Operating System: NixOS 24.11
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.6.0
Qt Version: 6.7.2
Kernel Version: 6.6.53 (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 7840U w/ Radeon 780M Graphics
Memory: 60.6 GiB of RAM
Graphics Processor: AMD Radeon 780M
Manufacturer: Framework
Product Name: Laptop 13 (AMD Ryzen 7040Series)
System Version: A7

Browser and version: Firefox 
Add-on version: 2.2

**Comment by rugk** [comment]
Hmm likely due to scripts checking/injecting stuff… though I tried to reproduce it with your link and while the website is slow, (especially the white page is loading very long) I did not found a [unresponsive script warning](https://support.mozilla.org/kb/warning-unresponsive-script).

Maybe a screencast would help?

Anyway, help is needed, because I don't really know what would cause these performance issues…
