### ISSUE TITLE
Support for Mastodon v4

### ISSUE THREAD

**Issue by austinhuang0131** [rugk/mastodon-simplified-federation#77]
## Background
Mastodon removed links to interact remotely and now asks you to just copy the link to the search box (which in my opinion greatly discourages decentralization).

## Proposed solution
Inject HTML to rewrite the buttons...?

## Alternatives
Right click menu...?

**Comment by rugk** [comment]
Is this live on mastodon.social?

If so that is uff, as it changes the whole way this extension works. It now cannot just intercept URLs, but indeed needs to rely on injection.

**Comment by StormPooper** [comment]
> Is this live on mastodon.social?

Yes, mastodon.social is running v4.0.0rc1.

**Comment by austinhuang0131** [comment]
Also, the interface link is now `https://example.instance/@rugk@chaos.social/103810871178820703` without the `/web/` anymore

**Comment by veale** [comment]
There is also this relevant new issue on the Mastodon page https://github.com/mastodon/mastodon/issues/20296 which flags that new Web APIs are available that can register websites as handlers for other types of links. This seems like the longer term solution but no idea if it will get takeup.

**Comment by hueyy** [comment]
I think HTML injection can only be done via a content script, in which case there are 2 ways to go about this:

1. By running a content script on all URLs that checks if the page is a Mastodon v4 page, and then injects the appropriate HTML. This has the downside of requiring permission to run a content script on all URLs.
2. By programmatically running a content script in either the active tab or all tabs. The content script then injects the appropriate HTML. I think this can be done with the existing set of permissions.

In both cases, the content script locates the follow button and adds an eventListener that redirects on click to https://example.instance/authorize_interaction?uri=@rugk@chaos.social, and then preventsDefault and further propagation of the event. And analogous injections for the interaction buttons too (i.e. reply, boost, and favourite).

If this makes sense, I'm happy to send in a PR implementing it. But since it appears to quite different from how the extension currently operates and this would also be my first contribution to the repo, I'd appreciate @rugk's thoughts on this.

**Comment by StormPooper** [comment]
Just wanted to mention that https://github.com/mastodon/mastodon/releases/tag/v4.0.0 has just been officially released, so we'll start to see servers more servers stop working with the extension soon. hueyy's second proposal sounds like a decent plan to me.

**Comment by atomicwrites** [comment]
Yeah I joined mastodon yesterday, and all the servers I have tested are on v4 and don't work with the extension.

**Comment by rugk** [comment]
@atomicwrites We're at it, thanks again to @hueyy who works on that in #82.

**Comment by RodriMora** [comment]
> @atomicwrites We're at it, thanks again to @hueyy who works on that in #82.

seems like the fix is already g2g, when should we expect to have an update on the extension? Thanks a lot!

**Comment by le-jun** [comment]
Just so you know someone released a Firefox plugin for v4 follows, if that may help development here.

https://github.com/raikasdev/mastodon4-redirect

**Comment by 2rs2ts** [comment]
I would like to share that [another extension](https://addons.mozilla.org/en-US/firefox/addon/mastodon4-redirect/) has popped up that apparently handles the Mastodon 4 redirection. I haven't tested it since it also requests all site data and has no reviews, and I don't know if it'll play nice with Pleroma etc., but it might be worth taking a peek at how they accomplish it.

**Comment by DiThi** [comment]
All of the instances I've tried it with are v4, so I think the currently published version is broken for most people. I made a little userscript to use until the fixed version is published (replace example.com by your instance, then use with F2).

```
// ==UserScript==
// @name         Go to my mastodon instance
// @match        *://*/*
// @grant        none
// ==/UserScript==

// PUT YOUR INSTANCE BELOW
const INSTANCE = 'example.com';

addEventListener('keydown', (e)=>{
    if(e.key === 'F2' && document.body.firstElementChild.id === 'mastodon'){
        e.preventDefault();
        let parts = location.href.split('/').splice(0,4);
        if(parts[3].indexOf('@',1) === -1) parts[3] += '@'+parts[2];
        parts[2] = INSTANCE;
        location.href = parts.join('/');
    }
})
```

**Comment by stefandesu** [comment]
@DiThi I just built myself a similar UserScript (although yours is so much simpler), but my instance will only show a spinner for accounts it hasn't yet interacted with. As soon as I open the profile once (e.g. through my instance's search), the URL will work. For now, I'm using the `/authorize_interaction?uri=` endpoint which works well.

**Comment by evmcl** [comment]
Will there be a new release of the extension any time soon so we can reap the benefits of this fix?

**Comment by DiThi** [comment]
Yeah I think an imperfect addon that can only follow people and maybe fav/boost sometimes is much better than an outdated that can't do even that. I used this addon a few times, but very rarely because so few instances I encounter are v3 now.
