### ISSUE TITLE
Smaller popup (non-full screen)

### ISSUE THREAD

**Issue by naught101** [rugk/mastodon-simplified-federation#83]
Currently, when a follow link is clicked, I get a full-screen pop-up. I can un-maximise to get a nicely sized pop-up that is just wide enough for the content.

Is there a way to automatically have the pop-up made a smaller size? This would make it a little clearer to follow what's going on, I think.

**Comment by rugk** [comment]
AFAIK the popup size is decided by your browser respectively maybe Mastodon itself.

However, what you could do is enable the option to skip/ignore the popup altogether and thus just redirect to your site on your main page/the page you are on instead of a popup jumping up. See https://github.com/rugk/mastodon-simplified-federation/issues/44 for details.

Does that help in your use case?

**Comment by rugk** [comment]
Yes, this is about to be expected.

**Comment by rugk** [comment]
> if I click follow, I still get a pop-up, which closed itself quickly, before the redirect happens

Though I have an idea on how that could be improved/solved in the future: https://github.com/rugk/mastodon-simplified-federation/issues/86

Anyway, I consider this issue here to be resolved/handled in other issues or already implemented.
